### ISSUE TITLE
项目不规范，不推荐学习

### ISSUE THREAD

**Issue by dreamer2q** [shirne/chinese_chess#1]
开源项目不规范，造成不必要的困扰，不推荐学习

- pubspec.yml 文件里使用了本地库，但是这个库不在代码仓库里面。
- android gradle 下载连接被改成“test.test.com"不存在的本地域名。

**Comment by calcitem** [comment]
已通过 https://gitee.com/shirne/chinese_chess/pulls/1/commits 修复编译问题。

**Comment by shirne** [comment]
> 已通过 https://gitee.com/shirne/chinese_chess/pulls/1/commits 修复编译问题。

感谢，我看到了，稍后合并
