### ISSUE TITLE
Process.start 在release模式中调用的程序无法隐藏被调用的程序的界面 

### ISSUE THREAD

**Issue by LuckyLi706** [shirne/chinese_chess#2]
兄弟，请问这个问题你后面解决了嘛，我也遇到这个问题

**Comment by shirne** [comment]
应该是解决了，我这里win目录重建过了，最近没有注意过这个问题。
或者你可以参考我这个commit修改win目录下的原生代码试一下
https://github.com/shirne/chinese_chess/commit/9609f25b598dfd7e056d26421b2f0f294cb8cbeb

**Comment by LuckyLi706** [comment]
好的，谢谢，问题我在github上面找到了。和你的这个差不多

**Comment by shuangqiao999** [comment]
你好 有个开源免费的nnue中国象棋引擎 棋力强劲 项目地址 https://github.com/PikaCat-OuO/Pikafish
可以集成到你的象棋里吗？

**Comment by shirne** [comment]
> 你好 有个开源免费的nnue中国象棋引擎 棋力强劲 项目地址 https://github.com/PikaCat-OuO/Pikafish 可以集成到你的象棋里吗？

好像是国际象棋的，应该不能通用的吧

**Comment by shuangqiao999** [comment]
是中国象棋 当前棋力在旋风小虫以后 排名第三 开源免费的

**Comment by shirne** [comment]
> 是中国象棋 当前棋力在旋风小虫以后 排名第三 开源免费的

它协议是用的uci，初始化命令不一样，其它的相差不大，你可以在windows版中改下引擎路径和初始化命令，试一下
ucci -> uci

**Comment by shirne** [comment]
@shuangqiao999 3df65a46f964ef184f3b407d46b00cd1425aaa22

**Comment by wengxianxun** [comment]
安卓是不是还没内置这个引擎，好像跑不起来
