### ISSUE TITLE
gpl协议传染性太强

### ISSUE THREAD

**Issue by beijiejiangzhe** [shirne/chinese_chess#3]
gpl协议传染性太强

**Comment by calcitem** [comment]
由于象棋程序调用了遵循 GPL（GNU General Public License）许可的皮卡鱼，按照 GPL 许可证的规定，这个象棋程序必须以 GPL 许可证发布。GPL 许可证被设计为强制性地要求继承其开源协议，这是为了保护和扩大开源代码的自由使用、修改和分享。

换句话说，任何基于 GPL 许可证发布的软件（如 皮卡鱼）的二次开发或派生作品都需要遵循 GPL 许可证。这是 GPL 许可证的一个重要特性，也是许多开源软件能够广泛传播和使用的重要原因。

因此，对于你的担忧，我想说，如果想要进行二次开发，确实需要考虑 GPL 的要求。虽然 GPL 许可证有其传染性，但它的目的是为了保护开源代码的自由，确保每个人都能够使用、修改和再次发布这些代码。如果你担心 GPL 许可证的限制，那么在选用开源项目时，你可以考虑使用其他许可证的项目。
